version: '3.8'

services:
  app:
    image: ghcr.io/codebender37/testing:main
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  watchtower:
    image: containrrr/watchtower
    command:
      - --cleanup=true
      - --interval=30
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
