version: 2.1

jobs:
  release:
    docker:
      - image: python:3.11
    steps:
      - checkout
      - run:
          name: Install nvm and Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 20.12.2
            nvm use 20.12.2
            nvm alias default 20.12.2
      - run:
          name: Install semantic-release
          command: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github
      - run:
          name: Verify GH_TOKEN
          command: |
            if [ -z "$GH_TOKEN" ]; then echo "GH_TOKEN is not set"; exit 1; fi
      - run:
          name: Run semantic release
          command: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npx semantic-release

workflows:
  version: 2
  release:
    jobs:
      - release
